const AID={gold:[[10,2],[50,8],[100,15]],troops:[[10,3],[50,10],[100,18]]};
let relations=[],wars=[],warTurns=[],peaceTurns=[],peaceUntil=[],battleThisTurn=[],diplomacyTarget=null;
function resetDiplomacy(){relations=K.map(()=>K.map(()=>0));wars=K.map(()=>K.map(()=>false));peaceUntil=K.map(()=>K.map(()=>0));warTurns=K.map(()=>0);peaceTurns=K.map(()=>0);battleThisTurn=K.map(()=>false);diplomacyTarget=null;resetNationalState();const w=window.SAMGUK_WAKO_ID;if(Number.isInteger(w)&&count(w)>0)for(let k=0;k<K.length;k++)if(k!==w&&count(k)>0)wars[k][w]=wars[w][k]=true}
function atWar(k){if(k===window.SAMGUK_WAKO_ID)return false;return wars[k]?.some((v,j)=>v&&count(j)>0&&j!==window.SAMGUK_WAKO_ID)||false}
function fatigue(k){return Math.min(100,warTurns[k]||0)}
function drafted(i,base,commit=false,type='infantry'){const r=regions[i],amount=base*resourceDraft(i,type)*supplyFactor(i)*recruitmentEfficiency(i)*(100-fatigue(r.owner))/100+(r.draftCarry||0),whole=Math.floor(amount+1e-9);if(commit)r.draftCarry=Math.max(0,amount-whole);return whole}
function canAttack(a,b){if(a===b)return false;if(a===window.SAMGUK_WAKO_ID||b===window.SAMGUK_WAKO_ID)return true;return turn>=peaceUntil[a][b]}
function recordBattle(a,b){if(a===b)return;battleThisTurn[a]=true;battleThisTurn[b]=true}
function beginWar(a,b){if(a===b)return;wars[a][b]=wars[b][a]=true;if(a===window.SAMGUK_WAKO_ID||b===window.SAMGUK_WAKO_ID)return;peaceTurns[a]=peaceTurns[b]=0;if(!warTurns[a])warTurns[a]=1;if(!warTurns[b])warTurns[b]=1}
function cleanWars(){for(let k=0;k<K.length;k++){if(!count(k))for(let j=0;j<K.length;j++)wars[k][j]=wars[j][k]=false}}
function advanceWarFatigue(){cleanWars();for(let k=0;k<K.length;k++){if(atWar(k)){peaceTurns[k]=0;warTurns[k]++}else{peaceTurns[k]=Math.min(4,(peaceTurns[k]||0)+1);if(peaceTurns[k]>=4)warTurns[k]=0}}}
function applyNaturalWarPenaltyDecay(){cleanWars();for(let k=0;k<K.length;k++){const offset=(atWar(k)?1:0)+(battleThisTurn[k]?0:1);warTurns[k]=Math.max(0,(warTurns[k]||0)-offset)}battleThisTurn=K.map(()=>false)}
function availableAidTroops(){return regions.reduce((n,r)=>n+(r.owner===player?Math.max(0,r.troops-1):0),0)}
function recipientRegion(k){return CAPITALS.find(i=>regions[i].owner===k)??regions.findIndex(r=>r.owner===k)}
function giveAid(type,index){const k=diplomacyTarget,row=AID[type]?.[index];if(k===window.SAMGUK_WAKO_ID)return;if(!playing||busy||k===null||k===player||!count(k)||!row)return;const [amount,gain]=row;if(type==='gold'){if(gold<amount)return;gold-=amount}else{if(!transferSupport(player,k,amount))return;}relations[player][k]=relations[k][player]=Math.min(100,relations[player][k]+gain);log(K[k].name+'에 '+(type==='gold'?'금 ':'병력 ')+amount+' 지원 · 우호도 '+relations[player][k]);render();renderDiplomacy()}
function endWar(){const k=diplomacyTarget;if(k===window.SAMGUK_WAKO_ID){notify('왜구와는 종전이나 협상이 불가능합니다.');return}if(!playing||busy||k===null||!wars[player][k])return;wars[player][k]=wars[k][player]=false;peaceUntil[player][k]=peaceUntil[k][player]=turn+1;cleanWars();log(K[k].name+'와 종전 · 다음 턴까지 상호 공격 금지');render();renderDiplomacy()}
function relationAppearance(k){if(wars[player][k])return {icon:'😡',label:'전쟁 중',tone:'war'};if(peaceUntil[player][k]>turn)return {icon:'☮️',label:'종전 · 상호 공격 금지',tone:'peace'};const n=relations[player][k];return n>=80?{icon:'🤝',label:'매우 우호적',tone:'friendly'}:n>=40?{icon:'🙂',label:'우호적',tone:'friendly'}:{icon:'😐',label:'평화',tone:'neutral'}}
function renderDiplomacy(){const options=K.map((k,i)=>i!==player&&count(i)&&i!==window.SAMGUK_WAKO_ID?`<button data-diplomacy-target="${i}" aria-pressed="${diplomacyTarget===i}"><span class="relation-icon" aria-hidden="true">${relationAppearance(i).icon}</span><span>${k.name}</span></button>`:'').join('');let html=`<div class="destination-list">${options}</div>`;const k=diplomacyTarget;if(k!==null&&count(k)){html+=`<div class="diplomacy-summary"><h3>${K[k].name}</h3><div class="affinity-value"><span>♡ 우호도</span><strong>${relations[player][k]}<small> / 100</small></strong></div><p class="relation-status ${relationAppearance(k).tone}"><span class="relation-icon" aria-hidden="true">${relationAppearance(k).icon}</span>${relationAppearance(k).label}<small>전쟁 피로도 −${fatigue(k)}%</small></p></div>`;for(const [type,label] of [['gold','금전 지원'],['troops','병력 지원']])html+=`<h3>${label}</h3><div class="destination-list">${AID[type].map(([amount,gain],index)=>`<button data-aid-type="${type}" data-aid-index="${index}" ${busy||!playing||(type==='gold'?gold:availableAidTroops())<amount?'disabled':''}>${amount}${type==='gold'?'금':'명'} 지급<small>우호도 +${gain}</small></button>`).join('')}</div>`;html+=`<p class="subtext">보유 금 ${gold.toFixed(1)} · 지원 가능 병력 ${availableAidTroops()}명<br>병력은 각 영토에 1명씩 남기고 보병부터 차출해 상대의 보유 수도 또는 첫 영토에 보냅니다. 지원은 행동력을 사용하지 않습니다.</p>${wars[player][k]?'<button class="action" id="endWar">종전 · 다음 턴까지 상호 공격 금지</button>':''}`;html+=goldGiftUI(k)+supportRequestUI(k)}else html+='<p>외교할 국가를 선택하세요.</p>';$('diplomacyContent').innerHTML=html}
function openDiplomacy(){if(!playing||busy)return;if(diplomacyTarget===null||!count(diplomacyTarget))diplomacyTarget=K.findIndex((k,i)=>i!==player&&count(i)&&i!==window.SAMGUK_WAKO_ID);renderDiplomacy();$('diplomacyDialog').showModal()}
function initDiplomacy(){$('diplomacyButton').onclick=openDiplomacy;$('closeDiplomacy').onclick=()=>$('diplomacyDialog').close();$('diplomacyContent').onclick=e=>{const b=e.target.closest('button');if(!b||busy)return;if(b.dataset.diplomacyTarget!==undefined){diplomacyTarget=+b.dataset.diplomacyTarget;renderDiplomacy()}if(b.dataset.requestSupport!==undefined)requestSupport(+b.dataset.requestSupport);if(b.dataset.goldGift!==undefined)goldGift(+b.dataset.goldGift);if(b.dataset.aidType)giveAid(b.dataset.aidType,+b.dataset.aidIndex);if(b.id==='endWar')endWar()}}
