const COASTAL=new Set([0, 2, 3, 4, 5, 8, 9, 10, 11, 13, 14, 15, 16, 20, 22, 23, 25, 35, 36, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 57, 61, 63, 64, 66, 70, 71, 76, 84, 85, 86, 88, 91, 92, 96, 97, 98, 99, 100]);
const UNIQUE_BUILDINGS={tradePort:{name:'교역항',cost:100,description:'해안 전용 · 영토 금 수입 +20%',icon:'항',nation:1},forge:{name:'대장간',cost:80,description:'이 영토의 모든 병과 모집비 −15%',icon:'철',nation:3},jiangnanFort:{name:'강남성곽',cost:100,description:'방어 +20% · 궁병 수비 추가 +20%',icon:'곽',nation:10}};
let supportTurn=[],supportRequested=[];
function resetNationalState(){supportTurn=K.map(()=>0);supportRequested=K.map(()=>0)}
function recruitmentEfficiency(i){return nationHas(regions[i].owner,'agropastoral')&&['mountain','grass','steppe'].includes(terrainKind(i))?1.2:1}
function recruitmentCost(i,base,cavalry=false,type='infantry'){const resourceMult=typeof resourceRecruitCostMultiplier==='function'?resourceRecruitCostMultiplier(i,type,cavalry):1,isCavalry=cavalry||['cavalry','nomadCavalry','armoredCavalry'].includes(String(type||'')),steppeMult=isCavalry&&typeof steppeCavalryRecruitMultiplier==='function'?steppeCavalryRecruitMultiplier(i):1;return Math.ceil(base*(cavalry&&grassNetwork(regions[i].owner)?.9:1)*(cavalry&&nationHas(regions[i].owner,'nomad')?.7:1)*(regions[i].buildings.forge?.85:1)*resourceMult*steppeMult-1e-9)}
function cavalryType(k){return nationHas(k,'nomad')?'nomadCavalry':'cavalry'}
function uniqueBuildAllowed(i,key){const b=UNIQUE_BUILDINGS[key];return !b||(regions[i].owner===b.nation&&(key!=='tradePort'||COASTAL.has(i)))}
function nationalDefense(i){const r=regions[i],b=r.buildings;return (nationHas(r.owner,'defensive')?15:0)+(nationHas(r.owner,'jiangnan')?(b.wall?20:0)+(TERRAIN_RULES_DATA.areas[i].river?10:0):0)+(b.jiangnanFort?20:0)}
function supportActive(k){return nationHas(k,'confederation')&&supportTurn[k]===turn}
function receiveSupport(from,to,n){if(n>0&&from!==to&&nationHas(to,'confederation')&&!wars[from][to]&&(relations[from][to]>=80||nationHas(from,'confederation')))supportTurn[to]=turn}
function supportCapacity(k){return regions.reduce((sum,r)=>sum+(r.owner===k?Math.max(0,r.troops-1):0),0)}
function transferSupport(from,to,amount){if(supportCapacity(from)<amount||recipientRegion(to)<0)return false;let remaining=amount,moved=emptyUnits();for(const r of regions){if(r.owner!==from||!remaining)continue;let take=Math.min(remaining,Math.max(0,r.troops-1));const counts=unitCounts(r),sent=emptyUnits();for(const key of UNIT_KEYS){sent[key]=Math.min(take,counts[key]);take-=sent[key];remaining-=sent[key];moved[key]+=sent[key]}changeUnits(r,sent,-1)}changeUnits(regions[recipientRegion(to)],moved);receiveSupport(from,to,amount);return true}
function requestSupport(index){const k=diplomacyTarget,amount=[10,50,100][index];if(!playing||busy||ap<1||!amount||k===null||k===player||wars[player][k]||relations[player][k]<80||supportRequested[player]===turn||!count(k))return;if(!transferSupport(k,player,amount))return;supportRequested[player]=turn;ap--;log(K[k].name+' 지원군 '+amount+'명 합류');render();renderDiplomacy()}
function supportRequestUI(k){if(relations[player][k]<80||wars[player][k])return '';return `<h3>우호국 지원군 요청</h3><div class="destination-list">${[10,50,100].map((n,i)=>`<button data-request-support="${i}" ${busy||ap<1||supportRequested[player]===turn||supportCapacity(k)<n?'disabled':''}>${n}명 요청</button>`).join('')}</div><p class="subtext">우호도 80 이상 · 비전쟁 · 턴당 1회 · 행동 1. 상대 병력을 실제 차감합니다. 가야는 합류한 턴 공격 +30%.</p>`}
function nationalStatus(i){return `<p class="subtext">${COASTAL.has(i)?'해안 영토 · ':''}${supportActive(regions[i].owner)?'연합 지원: 이번 턴 공격 +30%':''}</p>`}
